### ISSUE TITLE
Lag that seems to be caused by CrazyEnchantments

### ISSUE THREAD

**Issue by cloakfox** [badbones69/Crazy-Enchantments#221]
Timings: https://timings.aikar.co/?id=03c05eded167402a88ff2d811106fe54#timings

**Comment by Joannou1** [comment]
Difficult to tell, but here are mine.
You can see significant amount of events under packet processing:

https://timings.aikar.co/?id=85c8a3d59ce0410181c9f5886a3bc20f#plugins

**Comment by cloakfox** [comment]
New timings after a optimization attempt lol
https://timings.aikar.co/?id=c7dfd949798f48e695e2622164f46ce6

Pretty sure it's crazyenchantments

**Comment by Joannou1** [comment]
I downloaded the source, replaced all PlayerMoveEvents to trigger once per second async, and adjusted the chance ratings per cycle.
Player tracker / potion effects / etc were ran sync in the async thread.
This resulted in the server not getting raped whenever people are moving around a lot.
I'll let the devs do it properly, because my fix reduces lag, but it's a bit janky and I had import it into maven and stuff
