### ISSUE TITLE
clicking on an item in menus normally picks up item

### ISSUE THREAD

**Issue by CozyCat** [badbones69/Crazy-Enchantments#414]
When I open the enchanter and then click on one of the stones, i just pick it up like its a normal chest. Same with every other item in other menus

**Comment by Hitosherizu** [comment]
You made a mistake in one of your files. Run it through a yaml parser

**Comment by badbones69** [comment]
This is either due to a broken config.yml file or you are using ids in the config.yml when using 1.13+ which 1.13+ does not support. If you are using IDs I recommend changing them to the new Material names. Also if your using 1.13+ make sure you are using the development builds as the 1.7.9.4 does NOT support 1.13+.

**Comment by ElGodyro** [comment]
Welp! Did you find a solution cause im having the same problem and i have no clue what to do :/

**Comment by badbones69** [comment]
@ElGodyro Check the console for an error and make a new issue with the error if it is there and if not pastebin your config and link it in the new issue.
